# theme: jekyll-theme-midnight
remote_theme: pmarsceill/just-the-docs

title: X-Update Manager
description: One-click to get and deploy modules and themes
baseurl: "/" # the subpath of your site, e.g. /blog

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Just the XCL Store on GitHub":
    - "https://github.com/xoopscube/xupdate-store"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2005-2022 The XOOPSCube Project. Distributed by BSD license and GPL V2.0 license"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/xoopscube/xupdate-store" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
color_scheme: nil
plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
