# Site settings
title: 'X-Update Store'
description: 'Get and deploy modules, preloads (plugin extension) and themes using X-Update Manager GUI one-click installation.'
url: 'http://xoopscube.github.io/xupdate-store/'
baseurl: '/xupdate-store'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

remote_theme: matthiaslischka/jekyll-uno
