# theme: jekyll-theme-midnight
remote_theme: pmarsceill/just-the-docs

title: Just the Docs
description: A Jekyll theme for documentation
baseurl: "/xupdate-store" # the subpath of your site, e.g. /blog
