# Site settings
title: 'X-Update Store'
description: 'Get and deploy modules, preloads (plugin extension) and themes with X-Update Manager GUI one-click installation.'
url: ''
baseurl: '/xupdate-store'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

remote_theme: moonwalk
